version: '3'
services:
  splunk:
    build: "splunk"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_USER: "root"
    ports:
      - "8000:8000"
      - "8088:8088" # http event collector
  webapp:
    build: "webapp"
    ports:
      - "8080:8080"
    depends_on:
      - splunk
    logging:
      driver: "splunk"
      options:
        splunk-token: "bb3714bf-b59c-4971-94b7-30c9244c803a"
        splunk-url: 'http://splunk:8088'
        splunk-verify-connection: 'false'
        splunk-format: 'json'
