FROM splunk/splunk:latest

ADD etc/apps/splunk_httpinput/local/inputs.conf /opt/splunk/etc/apps/splunk_httpinput/local/inputs.conf
ADD etc/apps/search/local/inputs.conf /opt/splunk/etc/apps/search/local/inputs.conf
ADD etc/apps/search/local/indexes.conf /opt/splunk/etc/apps/search/local/indexes.conf

